name: Kernel Module Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential linux-headers-$(uname -r)

      - name: Build Kernel Module
        run: |
          make

      - name: Verify build output
        run: |
          file *.ko

      - name: Commit changes with standard message
        run: |
          git add .
          git commit -m "[CI] Automated build and checks (K-PRZ)" || echo "No changes to commit"
          git push
